### ISSUE TITLE
CMU Panoptic file

### ISSUE THREAD

**Issue by D1vyansh** [HowieMa/NSRMhand#11]
Hi,

Thank you for such an amazing project and repository!

I was wondering if you can provide me the preprocessing file for the CMU Panoptic dataset as I want to learn more about the preprocessing steps of it and heatmap generation through your code. 
Hoping for a positive response!

**Comment by HowieMa** [comment]
Hi, you can find the preprocessed datasets from the [README.md ](https://github.com/HowieMa/NSRMhand/blob/master/README.md)
However, I cannot provide the preprocessing code as it was on my old computer which was broken :( 

The basic idea is very simple, and you can try to implement it by yourself: 
Firstly, get the coordinates of key points in the whole body image, and then get the bounding box value, and then crop the image, and then adjust the coordinates. 

For the heatmap generation, you can check this function: 
https://github.com/HowieMa/NSRMhand/blob/master/dataset/hand_ldm.py#L91

**Comment by D1vyansh** [comment]
Hey, Thanks for the quick response, it worked for me!
I have some doubts about the evaluation PCK metric in utils.py file, can you tell the size of the box [ variable - bb_size] what is the value of that?

**Comment by HowieMa** [comment]
> Hey, Thanks for the quick response, it worked for me!
> I have some doubts about the evaluation PCK metric in utils.py file, can you tell the size of the box [ variable - bb_size] what is the value of that?

Hi, this is just the tightest bounding box of the hand.

**Comment by D1vyansh** [comment]
Also, in your paper, it is mentioned: "All hand image patches are resized to 368×368 before fed into our model, yielding 46×46 representation maps".  So is the final evaluation done on keypoints extracted from a 46x46 size heatmaps while the PCK threshold is [σ * (im_size/2.2)]. where σ ranges from 0 to 1 and im_size is the width of the cropped image?

**Comment by HowieMa** [comment]
> Also, in your paper, it is mentioned: "All hand image patches are resized to 368×368 before fed into our model, yielding 46×46 representation maps". So is the final evaluation done on keypoints extracted from a 46x46 size heatmaps while the PCK threshold is [σ * (im_size/2.2)]. where σ ranges from 0 to 1 and im_size is the width of the cropped image?

Hi, actually, I perform the evaluation on the original image scale, but it should be nearly the same as the evaluation on the 46 * 46 heatmap. 
For example, the original image for cropped hand has size 256 * 256, I will firstly resize it to 368 * 368, and send it to the model. The output heatmap has size 46 * 46, then I can get the location of the peak value. For example, the peak's coordinate in the 46 * 46 heatmap is (23,23). Then its location in the original image is 23 * 256 / 46 = 128. If the ground truth location is (130, 130). Then I can calculate the PCK by 
sqrt ((130 - 128)**2 + (130 - 128)^^2 ) < sigma * 256 / 2.2

You can easily find all solutions to your questions from here. Thanks! 
https://github.com/HowieMa/NSRMhand/blob/f4640d1a7b0e2b9483caa6ec4e95b5340d6e6d88/src/utils.py#L48
https://github.com/HowieMa/NSRMhand/blob/f4640d1a7b0e2b9483caa6ec4e95b5340d6e6d88/src/utils.py#L77
