### ISSUE TITLE
predict two hands from single picture

### ISSUE THREAD

**Issue by qdd1234** [HowieMa/NSRMhand#13]
Hi,thanks for your wonderful work.I want to ask whether model can predict two hands from single RGB picture?

**Comment by HowieMa** [comment]
Sorry, it cannot. You can use other datasets like InterHand to finetune it.

**Comment by qdd1234** [comment]
If I use Top-down approach, whether model can predict two hand from single RFB picture?

**Comment by HowieMa** [comment]
You need to crop two hands firstly and send them to the model separately, just like what people do for the top-down human pose estimation. 
BTW, the released model is simply trained on the Panoptic hand pose dataset, which only contains images in the panoptic studio. Thus it may not work well on other scenes.

**Comment by qdd1234** [comment]
Hi，When I use your pretarined model to inference,I meet a issue shown in the picture
![image](https://user-images.githubusercontent.com/68497831/111729958-3e3e7d80-88ab-11eb-8d5e-d4b167b18acc.png)
Could you help me solve this problem

**Comment by HowieMa** [comment]
Please see #4 
This is simply because you directly use CPU to inference.
