### ISSUE TITLE
The results of other test images is error

### ISSUE THREAD

**Issue by ZYzhouya** [HowieMa/NSRMhand#14]
When I test on the given image, the result is right.
But when I test on my test image, the result is error as below:
![image](https://user-images.githubusercontent.com/23133212/112631963-80029180-8e72-11eb-8256-5d24ef7cec16.png)

Is there anything wrong of my experiment?

**Comment by HowieMa** [comment]
The model is only trained with the cropped hand in the panoptic data, where the scene is limited. 
You may expect to finetune the model on other datasets to get a better result.
