### ISSUE TITLE
Encounter segfault when running inference.py

### ISSUE THREAD

**Issue by HollyDQWang** [HowieMa/NSRMhand#15]
Running inference.py on Ubuntu and encountered segfault on line
117     state_dict = torch.load(args.resume)
Would you mind suggesting any possible cause that this might be happening?

**Comment by HollyDQWang** [comment]
Okay this is resolved by specifying torch.load(args.resume, map_location=torch.device('cuda'))  and commenting out line 115 for some reason. Referenced this post here https://discuss.pytorch.org/t/segmentation-fault-when-loading-weight/1381

**Comment by HowieMa** [comment]
Sorry for the inconvenience. The model I uploaded has the device CUDA, and you may directly load it on the CPU.  I will update the version of the model later and make it feasible for the CPU.
