### ISSUE TITLE
train dataset  download

### ISSUE THREAD

**Issue by yy2yy** [HowieMa/NSRMhand#3]
Thanks for pretty project. Where to download the training data?I am looking forward to receiving your reply。

**Comment by zxfzqf** [comment]
@yy2yy  CMU Panoptic HandDB: http://domedb.perception.cs.cmu.edu/handdb.html

**Comment by yy2yy** [comment]
> @yy2yy  CMU Panoptic HandDB: http://domedb.perception.cs.cmu.edu/handdb.html

Do you have the reasoning code to load your own training model? Could you share it? Thank you very much!

**Comment by HowieMa** [comment]
@zxfzqf  Thank you for providing the link to Panoptic hand dataset. @yy2yy  I also release the preprocessed hand dataset, you can download it from [here](https://www.dropbox.com/s/ob0pbssocwszh9v/CMUhand.tar?dl=0) 
For the copyright issue, please DONOT duplicate it for any commercial purposes, and the copyright still belongs to Panoptic. Thank you!

**Comment by yy2yy** [comment]
> @zxfzqf  Thank you for providing the link to Panoptic hand dataset. @yy2yy  I also release the preprocessed hand dataset, you can download it from here
> For the copyright issue, please DONOT duplicate it for any commercial purposes, and the copyright still belongs to Panoptic. Thank you!

Thank you very much！
