### ISSUE TITLE
mediapipe hand landmark detect

### ISSUE THREAD

**Issue by aa12356jm** [HowieMa/NSRMhand#5]
hi ,thank you for your greate work ,have you tested the mediapipe handTracking demo? it works very good , I analyze the mediapipe handTracking model, it is very simple ,but  I can't do it with the precision，can you give me some ideas about it?  thanks

**Comment by noahzhy** [comment]
@aa12356jm I am also doing same work like mediapipe hand tracking, did you focus on palm detector? Or trained on synthetic dataset?
